### ISSUE TITLE
Missing API: SqlGeography.Parse() and SqlGeometry.Parse()

### ISSUE THREAD

**Issue by MaceWindu** [dotMorten/Microsoft.SqlServer.Types#13]
During migration of our tests to support this project, I discovered that SqlGeography.Parse()  and SqlGeometry.Parse() APIs are missing. Any plans to add them?

**Comment by dotMorten** [comment]
Thanks! I'll look into porting my old WKT Reader over - my main goal was to be able to query Spatial Types in SqlServer.

Having said that, parsing from WKT is extremely expensive and not something I'd recommend doing.
On the other hand, I should look into getting WKB support put in as well, since that performs much Much MUCH better :-)

**Comment by dotMorten** [comment]
I did a first pass at a WKT parser and pushed it here. It's somewhat untested (just two unit tests so far), but wanted to get it in for you try out, as it might be a little while before I get a chance to write some more tests.
Any feedback on how it works are much appreciated!

**Comment by dotMorten** [comment]
Thank you! These test cases are great. I'll try and look at it tonight (althought I did a few tests parsing those WKTs specifically, and things seemed fine except Lat/Long is swapped in geography, so might be something else)

**Comment by dotMorten** [comment]
@MaceWindu Again thank you. Especially one of the tests pointed out a really really bad bug. I have all the tests you shared above passing now. Do you mind trying again, and please let me know if anything else fails? Thanks!
